# Site settings
title: Language Blog, Natural Language Processing blog
email: antonio.balvet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Natural Language Processing has been around for over 40 years. So, what can you really do with it? This blog is about tinkering and experimenting with NLP libraries, both well established platforms as well as (presumably) new ideas.
baseurl: "abalvet.githu.io/nlpblog" # the subpath of your site, e.g. /blog/
url: "http://github.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  abalvet

# Build settings
markdown: kramdown
